name: Pak Takis

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make date
      run: echo "THEDATE=$(git rev-parse --abbrev-ref HEAD)-$(date +%Y-%m-%d)" >> $GITHUB_ENV
    - name: Make dummy package lock
      run: echo '{"name":"dummy","version":"1.0.0","lockfileVersion":3,"requires":true,"packages":{}}}' > package-lock.json
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    - name: Download PaK3
      run: git clone https://github.com/UnmatchedBracket/PaK3
    - name: Download PaK3`s dependencies
      run: bash -c "cd PaK3; npm i"
    - name: Run PaK3
      run: node PaK3/main.js src/ TakisBuild-${{ env.THEDATE }}.pk3
    # -$(date '+%d-%m-%Y')
    - name: Upload Takis - Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: 'takis.zip'
        path: "TakisBuild-${{ env.THEDATE }}.pk3"
        if-no-files-found: error
    - name: Upload Takis - Discord
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: TakisBuild-${{ env.THEDATE }}.pk3
